/*
  Warnings:

  - The values [TASK_COMPLETED,TASK_COMMENTED,SPRINT_REMINDER,WORKSPACE_INVITE] on the enum `NotificationType` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "NotificationType_new" AS ENUM ('WORKSPACE_CREATED', 'WORKSPACE_UPDATED', 'WORKSPACE_DELETED', 'WORKSPACE_MEMBER_INVITED', 'WORKSPACE_MEMBER_REMOVED', 'WORKSPACE_ROLE_UPDATED', 'WORKSPACE_INVITE_ACCEPTED', 'WORKSPACE_INVITE_DECLINED', 'PROJECT_CREATED', 'PROJECT_MEMBER_ADDED', 'PROJECT_DELETED', 'PROJECT_UPDATED', 'PROJECT_MEMBER_JOINED', 'PROJECT_MEMBER_REMOVED', 'PROJECT_MEMBER_INVITED', 'SPRINT_CREATED', 'SPRINT_UPDATED', 'SPRINT_DELETED', 'SPRINT_STARTED', 'SPRINT_COMPLETED', 'TASK_ADDED_TO_SPRINT', 'TASK_REMOVED_FROM_SPRINT', 'TASK_CREATED', 'TASK_UPDATED', 'TASK_DELETED', 'TASK_ASSIGNED', 'TASK_STATUS_UPDATED', 'TASK_MOVED_TO_SPRINT', 'TASK_MOVED_TO_BACKLOG', 'TASK_COMMENT_ADDED', 'TASK_COMMENT_DELETED', 'TASK_LINKED', 'TASK_LINK_REMOVED', 'TASK_LINK_UPDATED', 'SYSTEM');
ALTER TABLE "Notification" ALTER COLUMN "type" TYPE "NotificationType_new" USING ("type"::text::"NotificationType_new");
ALTER TYPE "NotificationType" RENAME TO "NotificationType_old";
ALTER TYPE "NotificationType_new" RENAME TO "NotificationType";
DROP TYPE "public"."NotificationType_old";
COMMIT;
